-- Staging table for player identity corrections.
--
-- Write-only destination of UtilComponent.review_player_identities(); read by
-- UtilComponent.apply_player_identity_reviews(). Nothing here is authoritative:
-- util.player and util.player_source_id stay the system of record, and a row is
-- only ever applied by the second method.
--
-- One row describes one proposed move. The subject is the source id that should
-- end up somewhere else (subject_player_key is the player it currently sits on,
-- null for a backlog id that has no player yet). The target is the player it
-- should join, for 'link' and 'merge'; 'new' instead carries proposed_name.
--
-- subject_player_key and target_player_key are deliberately plain integers, not
-- foreign keys: applying a merge deletes the subject player, and the log row
-- has to outlive it to record what happened.
--
-- input_hash is the idempotency key: re-running the reviewer over an unchanged
-- candidate inserts nothing.

BEGIN;

CREATE TABLE IF NOT EXISTS util.player_identity_review (
    review_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin             text NOT NULL,
    platform           text,
    source_id          bigint,
    source_name        text,
    subject_player_key integer,
    proposal           text NOT NULL,
    target_player_key  integer,
    proposed_name      text,
    confidence         double precision,
    reason             text,
    model              text,
    model_version      text,
    input_hash         text NOT NULL UNIQUE,
    status             text NOT NULL DEFAULT 'pending',
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS player_identity_review_status_ix
    ON util.player_identity_review (status);

COMMIT;
