-- Player identity: util.player + util.player_source_id, replacing the wide,
-- name-keyed util.conformed_player_id.
--
-- Why the reshape. conformed_player_id carried one column pair per platform
-- ({source}_id, {source}_name) with no primary key, no unique constraint and no
-- index. A new source could only arrive by matching a name, and when the match
-- missed the miss was appended as a new player: 1158 rows held 1128 distinct
-- names, and all 30 duplicates were one player split in two (a nba/espn/yahoo
-- row plus a statyx-only row with a null nba_id). Nothing about that shape could
-- detect it, because there was no key to conflict on.
--
-- Keying the mapping on (platform, source_id) makes the split inexpressible: a
-- source id resolves to exactly one player_key, and a re-run of the build can
-- never create a second row for an id it has already seen. Idempotency comes
-- from the key rather than from the matcher being right.
--
-- Platform vocabulary is lowercase throughout util.* ('nba', 'espn', 'statyx').
-- fty.* stores 'ESPN'/'Yahoo', so reads of those tables lower() it.

BEGIN;

-- ---------------------------------------------------------------- name key

-- Names are matched on this form, never raw. The sources disagree on accents,
-- punctuation and stray whitespace for the same player — nba reports "Egor
-- Dëmin" where espn and statyx report "Egor Demin", "Norris  Cole" carries a
-- double space, and espn's "P.J. Hairston" is nba's "PJ Hairston". Matching raw
-- strings splits those into separate players, which is the exact failure this
-- reshape exists to end.
--
-- IMMUTABLE so it can be indexed.
CREATE OR REPLACE FUNCTION util.norm_name(name text) RETURNS text AS $$
    SELECT lower(regexp_replace(
        translate(name,
            'áàâäãåéèêëíìîïóòôöõúùûüýÿçñšžÁÀÂÄÃÅÉÈÊËÍÌÎÏÓÒÔÖÕÚÙÛÜÝÇÑŠŽ',
            'aaaaaaeeeeiiiiooooouuuuyycnszAAAAAAEEEEIIIIOOOOOUUUUYCNSZ'),
        '[^a-zA-Z]', '', 'g'))
$$ LANGUAGE sql IMMUTABLE STRICT;

-- ---------------------------------------------------------------- identity

CREATE TABLE util.player (
    player_key     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conformed_name varchar NOT NULL,
    needs_review   boolean NOT NULL DEFAULT false
);

-- Deliberately NOT unique. Two genuinely different players can share a name,
-- and forcing uniqueness would make that case unrepresentable. What protects
-- against accidental duplication is the matcher, which only links a source id
-- to a name that matches exactly one player and otherwise leaves it unmatched
-- and visible in util.unmatched_player_source_vw.
CREATE INDEX player_norm_name_ix ON util.player (util.norm_name(conformed_name));

CREATE TABLE util.player_source_id (
    platform    varchar NOT NULL,
    source_id   bigint  NOT NULL,
    source_name varchar,
    player_key  integer NOT NULL REFERENCES util.player (player_key),
    PRIMARY KEY (platform, source_id)
);

CREATE INDEX player_source_id_player_key_ix ON util.player_source_id (player_key);

-- ---------------------------------------------------------------- seed

-- One player per distinct NORMALISED name. This is also what merges the 30
-- splits: both rows of a split share the name, so both sides' source ids end up
-- attached to the same player_key below. No separate repair statement is needed
-- — the grain change performs the fix. min() picks a stable representative
-- spelling where variants exist; a human can correct it via needs_review.
INSERT INTO util.player (conformed_name)
SELECT min(conformed_name)
FROM util.conformed_player_id
WHERE conformed_name IS NOT NULL
GROUP BY util.norm_name(conformed_name);

-- Unpivot the wide columns. Names are stored as '' rather than NULL in the old
-- table, hence nullif(); ids are already NULL when absent. Each {source}_id was
-- verified unique before this ran (nba 1122, espn 631, yahoo 614, statyx 504),
-- so no row is at risk of colliding on the new primary key.
INSERT INTO util.player_source_id (platform, source_id, source_name, player_key)
SELECT src.platform, src.source_id, src.source_name, p.player_key
FROM util.conformed_player_id c
JOIN util.player p
  ON util.norm_name(p.conformed_name) = util.norm_name(c.conformed_name)
CROSS JOIN LATERAL (
    VALUES ('nba',    c.nba_id,    nullif(c.nba_name, '')),
           ('espn',   c.espn_id,   nullif(c.espn_name, '')),
           ('yahoo',  c.yahoo_id,  nullif(c.yahoo_name, '')),
           ('statyx', c.statyx_id, nullif(c.statyx_name, ''))
) AS src(platform, source_id, source_name)
WHERE src.source_id IS NOT NULL;

COMMIT;
