-- Player identity: util.player + util.player_source_id, replacing the wide,
-- name-keyed util.conformed_player_id.
--
-- Why the reshape. conformed_player_id carried one column pair per platform
-- ({source}_id, {source}_name) with no primary key, no unique constraint and no
-- index. A new source could only arrive by matching a name, and when the match
-- missed the miss was appended as a new player: 1158 rows held 1128 distinct
-- names, and all 30 duplicates were one player split in two (a nba/espn/yahoo
-- row plus a statyx-only row with a null nba_id). Nothing about that shape could
-- detect it, because there was no key to conflict on.
--
-- Keying the mapping on (platform, source_id) makes the split inexpressible: a
-- source id resolves to exactly one player_key, and a re-run of the build can
-- never create a second row for an id it has already seen. Idempotency comes
-- from the key rather than from the matcher being right.
--
-- Platform vocabulary is lowercase throughout util.* ('nba', 'espn', 'statyx',
-- 'yahoo'). fty.* stores 'ESPN'/'Yahoo', so reads of those tables lower() it.
--
-- DDL ONLY. On an empty database, run this file, then
-- dev/build_player_identity_views.sql, then hub.util.conform_player_ids() to
-- populate both tables from util.player_directory_vw. The one-time seed from the
-- retired crosswalk has been removed.
--
-- player_source_id is NOT fully reconstructible from util.player_directory_vw
-- alone: the directory never reports espn/yahoo ids for players outside the
-- seasons fty holds data for, and the retired table held some of those. Back up
-- player_source_id before any destructive step.

BEGIN;

-- ---------------------------------------------------------------- identity

CREATE TABLE util.player (
    player_key     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conformed_name varchar NOT NULL,
    needs_review   boolean NOT NULL DEFAULT false
);

-- Deliberately NOT unique, and deliberately unindexed: two genuinely different
-- players can share a name, and matching is a Python fold over a few thousand
-- rows rather than a SQL lookup, so no functional index is needed. What protects
-- against accidental duplication is the matcher, which only links a source id to
-- a name that matches exactly one player and otherwise leaves it unmatched and
-- visible in util.unmatched_player_source_vw.
CREATE TABLE util.player_source_id (
    platform    varchar NOT NULL,
    source_id   bigint  NOT NULL,
    source_name varchar,
    player_key  integer NOT NULL REFERENCES util.player (player_key),
    PRIMARY KEY (platform, source_id)
);

CREATE INDEX player_source_id_player_key_ix ON util.player_source_id (player_key);

COMMIT;
