-- Player identity: util.player + util.player_source_id, replacing the wide,
-- name-keyed util.conformed_player_id.
--
-- Why the reshape. conformed_player_id carried one column pair per platform
-- ({source}_id, {source}_name) with no primary key, no unique constraint and no
-- index. A new source could only arrive by matching a name, and when the match
-- missed the miss was appended as a new player: 1158 rows held 1128 distinct
-- names, and all 30 duplicates were one player split in two (a nba/espn/yahoo
-- row plus a statyx-only row with a null nba_id). Nothing about that shape could
-- detect it, because there was no key to conflict on.
--
-- Keying the mapping on (platform, source_id) makes the split inexpressible: a
-- source id resolves to exactly one player_key, and a re-run of the build can
-- never create a second row for an id it has already seen. Idempotency comes
-- from the key rather than from the matcher being right.
--
-- Platform vocabulary is lowercase throughout util.* ('nba', 'espn', 'statyx',
-- 'yahoo'). fty.* stores 'ESPN'/'Yahoo', so reads of those tables lower() it.
--
-- DDL ONLY. The seed from util."conformed_player_id_RETIRED" now lives in Python
-- — UtilComponent.build_player_identity() — because name normalisation moved out
-- of SQL (see below), and matching runs on both Postgres and CockroachDB with
-- no user-defined function. After running this file on an empty database, call
-- hub.util.build_player_identity(), then dev/build_player_identity_views.sql,
-- then hub.util.conform_player_ids() for anything the directory reports beyond
-- the retired table.
--
-- The retired table is still worth keeping until you are satisfied: it holds
-- espn/yahoo ids the live directory never reports (players outside the seasons
-- fty has data for), so player_source_id is NOT fully reconstructible from
-- util.player_directory_vw alone. Do not drop it before backing up
-- player_source_id.

BEGIN;

-- ---------------------------------------------------------------- identity

CREATE TABLE util.player (
    player_key     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conformed_name varchar NOT NULL,
    needs_review   boolean NOT NULL DEFAULT false
);

-- Deliberately NOT unique, and deliberately unindexed: two genuinely different
-- players can share a name, and matching is a Python fold over a few thousand
-- rows rather than a SQL lookup, so no functional index is needed. What protects
-- against accidental duplication is the matcher, which only links a source id to
-- a name that matches exactly one player and otherwise leaves it unmatched and
-- visible in util.unmatched_player_source_vw.
CREATE TABLE util.player_source_id (
    platform    varchar NOT NULL,
    source_id   bigint  NOT NULL,
    source_name varchar,
    player_key  integer NOT NULL REFERENCES util.player (player_key),
    PRIMARY KEY (platform, source_id)
);

CREATE INDEX player_source_id_player_key_ix ON util.player_source_id (player_key);

COMMIT;
